# Generated by Django 5.2.1 on 2026-06-23 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(default='WHATSAPP', max_length=20)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.worker')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('sunday_reference', models.DateField()),
                ('usher_id', models.CharField(max_length=50)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.worker')),
            ],
            options={
                'verbose_name_plural': 'Check-In Records',
                'unique_together': {('worker', 'sunday_reference')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
